### ISSUE TITLE
compile_commands.json loaded at startup

### ISSUE THREAD

**Issue by Trass3r** [harikrishnan94/cxx-compiler-explorer#1]
The json file seems to be loaded directly at extension activation when running the disasm command for the first time, so if there is an error like missing directory element the extension fails to load and you just get a puzzling command not found error.
Later, even if you fix the json you have to restart VSCode.

**Comment by harikrishnan94** [comment]
Yes, currently compile commands are loaded at extension startup. Will try to add support for it.

**Comment by harikrishnan94** [comment]
Fixed in v0.5.2
compile_commands.json file is now being watched by the extension, after it is loaded. So, any changes to the file should automatically trigger reload internally and VSCode need not be reloaded.
Also, the errors are now gracefully handled such that once the correct compile commands are found, the command can be re-run without reloading
